# Generated by Django 3.2.8 on 2021-10-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0014_auto_20211015_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chores_name', models.CharField(blank=True, default='', max_length=1000)),
                ('chores_code', models.CharField(blank=True, default='', max_length=1000)),
                ('cre_on', models.DateTimeField(blank=True, null=True)),
                ('last_updt_on', models.DateTimeField(blank=True, null=True)),
                ('cre_by', models.CharField(blank=True, default='', max_length=1000)),
                ('last_updt_by', models.CharField(blank=True, default='', max_length=1000)),
                ('category', models.IntegerField(blank=True, default=0, max_length=1000)),
                ('rank', models.IntegerField(blank=True, default=0, max_length=100)),
                ('points', models.IntegerField(blank=True, default=0, max_length=10000)),
                ('background_color', models.CharField(blank=True, default='', max_length=1000)),
                ('icon', models.FileField(upload_to='chore_icons/')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
