# Generated by Django 3.2.8 on 2021-10-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0015_auto_20211024_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore_table',
            name='category',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='chore_table',
            name='points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='chore_table',
            name='rank',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
