# Generated by Django 3.2.8 on 2021-10-24 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root', '0017_auto_20211024_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction_table',
            old_name='chores_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='transaction_table',
            name='cre_by',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='transaction_table',
            name='cre_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='transaction_table',
            name='last_updt_by',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='transaction_table',
            name='last_updt_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='transaction_table',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction_table',
            name='duration',
            field=models.TimeField(blank=True, default=''),
        ),
    ]
