# Generated by Django 3.2.8 on 2021-10-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0019_auto_20211024_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore_table',
            name='cre_by',
            field=models.CharField(blank=True, default='System', max_length=1000),
        ),
        migrations.AlterField(
            model_name='chore_table',
            name='last_updt_by',
            field=models.CharField(blank=True, default='System', max_length=1000),
        ),
        migrations.AlterField(
            model_name='transaction_table',
            name='cre_by',
            field=models.CharField(blank=True, default='System', max_length=1000),
        ),
        migrations.AlterField(
            model_name='transaction_table',
            name='last_updt_by',
            field=models.CharField(blank=True, default='System', max_length=1000),
        ),
    ]
